# Generated by Django 3.2 on 2022-11-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverifier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
    ]
