# Generated by Django 3.1.4 on 2021-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('MA', '남자'), ('FE', '여자')], default='MA', max_length=2),
        ),
    ]
