# Generated by Django 3.2 on 2022-11-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_phoneverifier_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_image',
        ),
    ]
