# Generated by Django 3.2 on 2022-11-13 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_profile_pic_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
