# Generated by Django 3.1.4 on 2021-02-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210202_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year_in_school',
            new_name='sex_choices',
        ),
    ]
