# Generated by Django 3.1.4 on 2021-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210202_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='크리에이터 여부'),
        ),
    ]
