# Generated by Django 3.1.4 on 2021-02-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_is_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
