# Generated by Django 3.1.4 on 2022-10-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_article',
        ),
    ]
