# Generated by Django 3.1.4 on 2022-10-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20221001_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
    ]
