# Generated by Django 3.1.4 on 2022-11-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20221003_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '프로필', 'verbose_name_plural': '프로필'},
        ),
    ]
