# Generated by Django 3.1.4 on 2022-10-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211015_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRequest',
        ),
        migrations.DeleteModel(
            name='UserShipping',
        ),
    ]
