# Generated by Django 3.2 on 2022-11-13 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
                ('reason', models.CharField(max_length=1024, verbose_name='지급, 회수 사유')),
                ('amount', models.IntegerField(default=0, help_text='지급 시 양수를, 회수 시 음수를 입력해 주세요.', verbose_name='지급, 회수 금액')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포인트 로그',
                'verbose_name_plural': '포인트 로그',
            },
        ),
    ]
