# Generated by Django 3.1.4 on 2022-10-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchKeywords',
        ),
    ]
