# Generated by Django 3.2 on 2022-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='hospital_detail',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='내원 병원 상세주소'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='has_alergy',
            field=models.CharField(choices=[('IS', '유'), ('NT', '무'), ('DO', '모름')], default='IS', max_length=2, verbose_name='알러지 유무 여부'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hospital',
            field=models.CharField(max_length=1024, verbose_name='내원 병원 주소'),
        ),
    ]
