# Generated by Django 3.2 on 2022-11-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_auto_20221111_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='hospital',
            new_name='hospital_address',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='hospital_detail',
            new_name='hospital_address_detail',
        ),
    ]
