# Generated by Django 3.2 on 2022-11-24 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
