# Generated by Django 3.2 on 2022-11-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_animal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sort',
            field=models.CharField(choices=[('DOG', '강아지'), ('CAT', '고양이'), ('ETC', '기타')], default='DOG', max_length=3, verbose_name='종류'),
        ),
    ]
