# Generated by Django 3.2 on 2022-11-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_alter_animal_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='hospital_address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='내원 병원 주소'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='interested_disease',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='관심 질병'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='kind',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='품종'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='몸무게'),
        ),
    ]
