# Generated by Django 3.2 on 2022-11-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_auto_20221128_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(blank=True, max_length=512, null=True, verbose_name='종')),
            ],
            options={
                'verbose_name': '종',
                'verbose_name_plural': '종',
            },
        ),
        migrations.CreateModel(
            name='AnimalKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=512, null=True, verbose_name='품종')),
                ('sort_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.sortanimal', verbose_name='반려 동물 종')),
            ],
            options={
                'verbose_name': '반려동물 품종',
                'verbose_name_plural': '반려동물 품종',
            },
        ),
    ]
