# Generated by Django 3.2 on 2022-11-12 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreview',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_users', to=settings.AUTH_USER_MODEL, verbose_name='좋아요한 사람들'),
        ),
    ]
