# Generated by Django 3.2 on 2022-11-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_hospitalreview_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalreview',
            name='receipt',
        ),
        migrations.CreateModel(
            name='HospitalRecieptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('hospital_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.hospitalreview', verbose_name='리뷰')),
            ],
            options={
                'verbose_name': '병원 영수증 이미지',
                'verbose_name_plural': '병원 영수증 이미지',
            },
        ),
    ]
