# Generated by Django 3.2 on 2022-11-23 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20221123_1722'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_auto_20221112_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreview',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AlterField(
            model_name='hospitalreview',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL, verbose_name='좋아요한 사람들'),
        ),
    ]
