# Generated by Django 3.2 on 2022-11-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20221123_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalreview',
            old_name='review',
            new_name='content',
        ),
    ]
