# Generated by Django 3.2 on 2022-11-23 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rename_review_hospitalreview_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalreview',
            name='rates',
            field=models.IntegerField(default=5, verbose_name='리뷰 별점'),
        ),
    ]
