# Generated by Django 3.2 on 2023-01-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20221123_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalreview',
            options={'ordering': ['-created_at'], 'verbose_name': '병원 리뷰', 'verbose_name_plural': '병원 리뷰'},
        ),
    ]
