# Generated by Django 3.1.4 on 2022-10-01 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=512, verbose_name='콜렉션 아이디')),
                ('name', models.CharField(max_length=512, verbose_name='팝업 이름')),
                ('thumbnail', models.CharField(max_length=1024, verbose_name='콜렉션 이미지 url')),
            ],
            options={
                'verbose_name': '팝업 콜렉션',
                'verbose_name_plural': '팝업 콜렉션',
            },
        ),
        migrations.CreateModel(
            name='SearchKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=64, null=True, verbose_name='키워드')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드',
            },
        ),
        migrations.CreateModel(
            name='ShippingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='요구사항')),
            ],
            options={
                'verbose_name': '배송 요청사항',
                'verbose_name_plural': '배송 요청사항',
            },
        ),
        migrations.CreateModel(
            name='UserShipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('big_address', models.CharField(max_length=2048, verbose_name='기본 주소')),
                ('small_address', models.CharField(blank=True, max_length=2048, null=True, verbose_name='상세 주소')),
                ('postal_code', models.CharField(max_length=32, verbose_name='우편 번호')),
                ('phone_number', models.CharField(max_length=32, verbose_name='휴대폰')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 배송지 설정')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '유저 배송지',
                'verbose_name_plural': '유저 배송지',
            },
        ),
    ]
