# Generated by Django 3.2 on 2022-11-11 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '자주 묻는 질문',
                'verbose_name_plural': '자주 묻는 질문',
            },
        ),
        migrations.CreateModel(
            name='HospitalReviewReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('O', '접수'), ('C', '확인완료')], max_length=1, verbose_name='상태')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalreview', verbose_name='리뷰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '병원 리뷰 신고',
                'verbose_name_plural': '병원 리뷰 신고',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=128, verbose_name='병원 업체명')),
                ('hospital_address', models.CharField(max_length=1024, verbose_name='병원 주소명')),
                ('user_name', models.CharField(max_length=128, verbose_name='신청자 명')),
                ('user_email', models.CharField(max_length=256, verbose_name='신청자 이메일')),
                ('user_phone', models.CharField(max_length=128, verbose_name='신청자 전화번호')),
                ('user_hospital', models.CharField(max_length=128, verbose_name='신청자 소속')),
                ('user_level', models.CharField(max_length=128, verbose_name='신청자 직책')),
                ('methods', models.CharField(max_length=128, verbose_name='제휴 및 문의 경로')),
                ('condition', models.CharField(choices=[('O', '접수'), ('C', '확인완료')], max_length=1, verbose_name='상태')),
                ('additional_info', models.TextField(verbose_name='비고')),
            ],
            options={
                'verbose_name': '제휴 및 광고 문의',
                'verbose_name_plural': '제휴 및 광고 문의',
            },
        ),
        migrations.CreateModel(
            name='HospitalReviewReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='customerservice.hospitalreviewreport', verbose_name='리뷰')),
            ],
            options={
                'verbose_name': '병원 리뷰 신고 이미지',
                'verbose_name_plural': '병원 리뷰 신고 이미지',
            },
        ),
    ]
