# Generated by Django 3.2 on 2022-11-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='FAQ 카테고리')),
            ],
            options={
                'verbose_name': 'FAQ 카테고리',
                'verbose_name_plural': 'FAQ 카테고리',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='공지사항 제목')),
                ('content', models.TextField(verbose_name='공지사항 내용')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
            },
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='faq',
            name='faq_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerservice.faqmenu', verbose_name='FAQ 카테고리'),
        ),
    ]
