# Generated by Django 3.2 on 2022-11-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('customerservice', '0002_auto_20221111_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalreviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.hospitalreview', verbose_name='리뷰'),
        ),
    ]
