# Generated by Django 3.2 on 2022-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0003_alter_hospitalreviewreport_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(default='공지', max_length=32, verbose_name='종류')),
                ('name', models.CharField(max_length=1024, verbose_name='알림 제목')),
                ('content', models.TextField(verbose_name='알림 내용')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
            },
        ),
    ]
