# Generated by Django 3.2 on 2022-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0006_auto_20221123_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='condition',
            field=models.CharField(choices=[('O', '접수'), ('C', '확인완료')], default='O', max_length=1, verbose_name='상태'),
        ),
    ]
