# Generated by Django 3.2 on 2022-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0007_alter_offer_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='notification',
            name='sort',
            field=models.CharField(default='공지', help_text='"공지", "포인트" 등 알림 종류가 들어갑니다.', max_length=32, verbose_name='종류'),
        ),
    ]
