# Generated by Django 3.2 on 2022-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0008_auto_20221205_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='사용자 알림 제거 여부'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='사용자 열람 여부'),
        ),
    ]
