# Generated by Django 3.2 on 2022-12-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0009_auto_20221205_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
    ]
