# Generated by Django 3.2 on 2023-01-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerservice', '0012_alter_appversion_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='버전'),
        ),
    ]
