# Generated by Django 3.2 on 2022-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='정확한 질병명')),
            ],
            options={
                'verbose_name': '질병 명',
                'verbose_name_plural': '질병 명',
            },
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='증상명')),
            ],
            options={
                'verbose_name': '증상 명',
                'verbose_name_plural': '증상 명',
            },
        ),
    ]
