# Generated by Django 3.2 on 2022-11-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20221112_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.ManyToManyField(to='disease.Symptom', verbose_name='증상'),
        ),
    ]
