# Generated by Django 3.1.4 on 2022-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=64, verbose_name='진료 동물')),
            ],
            options={
                'verbose_name': '진료 동물',
                'verbose_name_plural': '진료 동물',
            },
        ),
        migrations.CreateModel(
            name='BestPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='특화 분야')),
            ],
            options={
                'verbose_name': '특화 분야',
                'verbose_name_plural': '특화 분야',
            },
        ),
        migrations.CreateModel(
            name='HopitalPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='진료 항목')),
                ('price', models.CharField(max_length=128, verbose_name='가격')),
            ],
            options={
                'verbose_name': '병원비',
                'verbose_name_plural': '병원비',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='병원명')),
                ('number', models.CharField(max_length=64, verbose_name='연락처')),
                ('image', models.ImageField(upload_to='', verbose_name='병원 이미지')),
                ('intro', models.TextField(max_length=64, verbose_name='소개글')),
                ('available_time', models.CharField(max_length=512, verbose_name='영업 시간')),
                ('rest_date', models.CharField(max_length=512, verbose_name='휴무일')),
                ('available_animal', models.ManyToManyField(to='hospital.AvailableAnimal', verbose_name='진료 가능 동물')),
                ('best_part', models.ManyToManyField(to='hospital.BestPart', verbose_name='특화 분야')),
                ('hospital_price', models.ManyToManyField(to='hospital.HopitalPrice', verbose_name='병원비')),
            ],
            options={
                'verbose_name': '병원',
                'verbose_name_plural': '병원',
            },
        ),
    ]
