# Generated by Django 3.2 on 2022-11-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='intro',
            field=models.TextField(verbose_name='소개글'),
        ),
    ]
