# Generated by Django 3.1.4 on 2022-10-01 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=128, verbose_name='진료 항목')),
                ('receipt', models.ImageField(upload_to='', verbose_name='영수증')),
                ('review', models.TextField(verbose_name='리뷰 내용')),
                ('likes', models.IntegerField(verbose_name='좋아요 수')),
            ],
            options={
                'verbose_name': '병원 리뷰',
                'verbose_name_plural': '병원 리뷰',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='노출 여부'),
        ),
        migrations.CreateModel(
            name='HospitalReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hospital.hospitalreview', verbose_name='리뷰')),
            ],
            options={
                'verbose_name': '병원 리뷰 이미지',
                'verbose_name_plural': '병원 리뷰 이미지',
            },
        ),
        migrations.AddField(
            model_name='hospitalreview',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital', verbose_name='병원'),
        ),
        migrations.AddField(
            model_name='hospitalreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
