# Generated by Django 3.1.4 on 2022-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20221001_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreview',
            name='rates',
            field=models.FloatField(default=5, verbose_name='리뷰 별점'),
        ),
    ]
