# Generated by Django 3.1.4 on 2022-10-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospitalreview_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='도로명 주소'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='address_detail',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='상세 주소'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='경도'),
        ),
    ]
