# Generated by Django 3.2 on 2022-11-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20221112_1517'),
        ('customerservice', '0003_alter_hospitalreviewreport_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalReview',
        ),
        migrations.DeleteModel(
            name='HospitalReviewImage',
        ),
    ]
