# Generated by Django 3.1.4 on 2022-10-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20221002_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='image',
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='이미지')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='hospital.hospital', verbose_name='병원')),
            ],
            options={
                'verbose_name': '병원 이미지',
                'verbose_name_plural': '병원 이미지',
            },
        ),
    ]
