# Generated by Django 3.2 on 2022-11-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20221112_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
    ]
