# Generated by Django 3.2 on 2022-11-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_hospitalimage_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalimage',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital', verbose_name='병원'),
        ),
    ]
