# Generated by Django 3.2 on 2022-11-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_rename_recommend_number_hospital_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableanimal',
            old_name='animal',
            new_name='name',
        ),
    ]
