# Generated by Django 3.2 on 2022-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_bestpart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpart',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='아이콘'),
        ),
    ]
